# This file executes the tasks to actually do the installation. It's
# included from main.yml when that file determines that yes, we do
# need to update.
---

# Create a temporary directory in which to put the .dmg file and any
# other temporary files we might create.
- name: Create temporary directory
  tempfile:
    state: directory
    suffix: emacsformacosx
  register: tmpdir
  notify: emacsformacosx delete temp

- name: Download DMG
  get_url:
    # dest: "Emacs-{{ version }}-universal.dmg"
    dest: "{{ tmpdir.path }}"
    url: "https://emacsformacosx.com/emacs-builds/Emacs-{{ version }}-universal.dmg"
  register: dmg_dl
  notify: emacsformacosx delete temp

- debug: var=dmg_dl

# Create a directory to mount the .dmg file.
- name: Create mountpoint
  file:
    path: "{{ tmpdir.path }}/Emacs"
    state: directory
    mode: 0755
  notify: emacsformacosx delete temp

- name: Mount DMG
  command:
    argv:
      - hdiutil
      - attach
      - -mount
      - required
      - -mountpoint
      - "{{ tmpdir.path }}/Emacs"
      # The .dmg file that was downloaded earlier:
      - "{{ dmg_dl.dest }}"
  notify: emacsformacosx unmount dmg

- name: Install the application
  become: yes
  copy:
    src: "{{ tmpdir.path }}/Emacs/Emacs.app"
    remote_src: yes
    dest: "{{ dest_dir }}"
    # Overwrite the existing application, if any.
    force: yes
