# This is the main taks file for emacsformacosx. It checks whether
# it's necessary to replace the existing version, and farms out
# subtasks to other task files.
---

# Check whether an update is even needed
- name: Get the currently-installed version
  check_mode: no
  changed_when: no
  command:
    argv:
      - "{{ emacs_bin }}"
      - "--batch"
      - "--execute"
      - '(princ (format "%d.%d" emacs-major-version emacs-minor-version))'
  register: current_emacs_version

# - name: Get the latest available version
#   include_tasks: find_latest_version.yml
#   when:
#     version == "latest"

# Perform the actual installation if either a) the version check
# failes, or b) the version check shows that we're running a version
# other than the desired one.
- name: Do the installation
  include_tasks: install_emacs.yml
  when:
    current_emacs_version.stdout is version(version, '!=')
